---
- hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Do Something
      ansible.builtin.include: "{{ playbook_dir }}/tasks/some_task.yml"

- ansible.builtin.import_playbook: "{{ playbook_dir }}/tasks/roles.yml"
